import { describe, expect, test } from "bun:test"
import {
  buildPrCheckoutResult,
  formatPrCheckoutText,
  extractSessionUrlFromPrBody,
  extractSessionIdFromImportOutput,
} from "../../src/cli/cmd/pr"

describe("pr command unit helpers", () => {
  test("extractSessionUrlFromPrBody extracts valid opncd.ai share urls", () => {
    const body = "This PR was generated by an agent session: https://opncd.ai/s/ses_abc123_xyz. Review carefully."
    expect(extractSessionUrlFromPrBody(body)).toBe("https://opncd.ai/s/ses_abc123_xyz")

    expect(extractSessionUrlFromPrBody("No session url here")).toBeUndefined()
    expect(extractSessionUrlFromPrBody(null)).toBeUndefined()
    expect(extractSessionUrlFromPrBody(undefined)).toBeUndefined()
  })

  test("extractSessionIdFromImportOutput extracts imported session id", () => {
    const output = "Importing session...\nImported session: ses_xyz789\nDone."
    expect(extractSessionIdFromImportOutput(output)).toBe("ses_xyz789")

    expect(extractSessionIdFromImportOutput("No imported session")).toBeUndefined()
    expect(extractSessionIdFromImportOutput("")).toBeUndefined()
    expect(extractSessionIdFromImportOutput(null)).toBeUndefined()
  })

  test("buildPrCheckoutResult creates structured payload", () => {
    const result = buildPrCheckoutResult({
      pr: 42,
      branch: "pr/42",
      forkRemote: "octocat",
      session: "ses_123",
      sessionUrl: "https://opncd.ai/s/ses_123",
      isCrossRepository: true,
    })

    expect(result).toEqual({
      pr: 42,
      branch: "pr/42",
      checkedOut: true,
      forkRemote: "octocat",
      session: "ses_123",
      sessionUrl: "https://opncd.ai/s/ses_123",
      isCrossRepository: true,
    })
  })

  test("buildPrCheckoutResult omits undefined optional fields", () => {
    const result = buildPrCheckoutResult({
      pr: 99,
      branch: "feature-branch",
    })

    expect(result).toEqual({
      pr: 99,
      branch: "feature-branch",
      checkedOut: true,
    })
    expect(result.forkRemote).toBeUndefined()
    expect(result.session).toBeUndefined()
  })

  test("formatPrCheckoutText formats readable status lines", () => {
    const result = buildPrCheckoutResult({
      pr: 42,
      branch: "pr/42",
      forkRemote: "contributor",
      session: "ses_abc",
      sessionUrl: "https://opncd.ai/s/ses_abc",
    })

    const lines = formatPrCheckoutText(result)
    expect(lines).toContain("Successfully checked out PR #42 as branch 'pr/42'")
    expect(lines).toContain("Fork remote: contributor")
    expect(lines).toContain("Session imported: ses_abc")
    expect(lines).toContain("Session URL: https://opncd.ai/s/ses_abc")
  })
})
