import { describe, expect, test } from "bun:test"
import yargs, { type Argv } from "yargs"
import {
  PrCommand,
  buildPrCheckoutResult,
  formatPrCheckoutText,
  extractSessionUrlFromPrBody,
  extractSessionIdFromImportOutput,
} from "../../src/cli/cmd/pr"

describe("pr command unit helpers", () => {
  test("extractSessionUrlFromPrBody extracts valid opncd.ai share urls", () => {
    const body = "This PR was generated by an agent session: https://opncd.ai/s/ses_abc123_xyz. Review carefully."
    expect(extractSessionUrlFromPrBody(body)).toBe("https://opncd.ai/s/ses_abc123_xyz")

    expect(extractSessionUrlFromPrBody("No session url here")).toBeUndefined()
    expect(extractSessionUrlFromPrBody(null)).toBeUndefined()
    expect(extractSessionUrlFromPrBody(undefined)).toBeUndefined()
  })

  test("extractSessionIdFromImportOutput extracts imported session id", () => {
    const output = "Importing session...\nImported session: ses_xyz789\nDone."
    expect(extractSessionIdFromImportOutput(output)).toBe("ses_xyz789")

    expect(extractSessionIdFromImportOutput("No imported session")).toBeUndefined()
    expect(extractSessionIdFromImportOutput("")).toBeUndefined()
    expect(extractSessionIdFromImportOutput(null)).toBeUndefined()
  })

  test("buildPrCheckoutResult creates structured payload", () => {
    const result = buildPrCheckoutResult({
      pr: 42,
      branch: "pr/42",
      forkRemote: "octocat",
      session: "ses_123",
      sessionUrl: "https://opncd.ai/s/ses_123",
      isCrossRepository: true,
    })

    expect(result).toEqual({
      pr: 42,
      branch: "pr/42",
      checkedOut: true,
      forkRemote: "octocat",
      session: "ses_123",
      sessionUrl: "https://opncd.ai/s/ses_123",
      isCrossRepository: true,
    })
  })

  test("buildPrCheckoutResult omits undefined optional fields", () => {
    const result = buildPrCheckoutResult({
      pr: 99,
      branch: "feature-branch",
    })

    expect(result).toEqual({
      pr: 99,
      branch: "feature-branch",
      checkedOut: true,
    })
    expect(result.forkRemote).toBeUndefined()
    expect(result.session).toBeUndefined()
  })

  test("formatPrCheckoutText formats readable status lines", () => {
    const result = buildPrCheckoutResult({
      pr: 42,
      branch: "pr/42",
      forkRemote: "contributor",
      session: "ses_abc",
      sessionUrl: "https://opncd.ai/s/ses_abc",
    })

    const lines = formatPrCheckoutText(result)
    expect(lines).toContain("Successfully checked out PR #42 as branch 'pr/42'")
    expect(lines).toContain("Fork remote: contributor")
    expect(lines).toContain("Session imported: ses_abc")
    expect(lines).toContain("Session URL: https://opncd.ai/s/ses_abc")
  })
})

describe("PrCommand builder & options", () => {
  test("PrCommand registers number, branch, no-run, output, o, and json options", () => {
    expect(PrCommand.command).toBe("pr <number>")
    const builder = PrCommand.builder as (y: Argv) => Argv<any>
    const parser = builder(yargs())
    const options = (parser as any).getOptions()
    expect(options.key.number).toBeDefined()
    expect(options.key.branch).toBeDefined()
    expect(options.key.b).toBeDefined()
    expect(options.key["no-run"]).toBeDefined()
    expect(options.key.output).toBeDefined()
    expect(options.key.o).toBeDefined()
    expect(options.key.json).toBeDefined()
  })

  test("PrCommand parses options from arguments", async () => {
    const builder = PrCommand.builder as (y: Argv) => Argv<any>
    const parsed = await builder(yargs()).parseAsync([
      "--output",
      "pr-details.json",
      "--json",
      "-b",
      "my-custom-branch",
      "--no-run",
    ])
    expect(parsed.output).toBe("pr-details.json")
    expect(parsed.json).toBe(true)
    expect(parsed.branch).toBe("my-custom-branch")
    expect(parsed.run).toBe(false)
  })

  test("PrCommand parses -o short alias", async () => {
    const builder = PrCommand.builder as (y: Argv) => Argv<any>
    const parsed = await builder(yargs()).parseAsync(["-o", "pr.txt"])
    expect(parsed.output).toBe("pr.txt")
  })

  test("PrCommand parses positional number, short aliases -b and -o, and --json", async () => {
    const parsed = await yargs()
      .command({ ...PrCommand, handler: () => {} })
      .parseAsync(["pr", "123", "-b", "fix-bug", "-o", "pr.json", "--json"])
    expect(parsed.number).toBe(123)
    expect(parsed.branch).toBe("fix-bug")
    expect(parsed.b).toBe("fix-bug")
    expect(parsed.output).toBe("pr.json")
    expect(parsed.o).toBe("pr.json")
    expect(parsed.json).toBe(true)
  })
})
